apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - port: {{ .Values.paymentService.port }}
      targetPort: {{ .Values.paymentService.port }}
      nodePort: 30004
  type: NodePort
