"""initial

Revision ID: eed8be882f52
Revises: d18d60044e68
Create Date: 2026-04-24 05:13:06.963251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eed8be882f52'
down_revision: Union[str, None] = 'd18d60044e68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
