apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: {{ .Values.authService.replicas }}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: {{ .Values.authService.image }}:{{ .Values.authService.imageTag }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.authService.port }}
          env:
            - name: DATABASE_URL
              value: "postgresql+asyncpg://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@db-auth:5432/{{ .Values.authService.dbName }}"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: foodflow-secret
                  key: secret-key
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.authService.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
